name: cab_go_driver
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_database: ^10.0.16
  connectivity_plus: ^3.0.3
  google_maps_flutter: ^2.2.5
  outline_material_icons: ^0.1.1
  geolocator: ^9.0.2
  http: ^0.13.5
  provider: ^6.0.5
  flutter_polyline_points: ^1.0.0
  font_awesome_flutter: ^10.4.0
  animated_text_kit: ^4.2.2
  flutter_geofire: ^2.0.3
  firebase_messaging: ^14.3.0
  assets_audio_player: ^3.0.6
  toast: ^0.3.0
  maps_toolkit: ^2.0.1
  intl: ^0.17.0
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^5.0.8
  get: ^4.6.5
  get_it: ^7.2.0
  flutter_screenutil: ^5.7.0
  flutter_ringtone_player: ^3.2.0
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf