import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'cab_go': 'CabGo Driver',
          'login': 'Log In',
          'logout': 'Log Out',
          'home': 'Home',
          'search': 'Search',
          'get_started': 'Get Started',
          'letsRide': "Let's Ride",
          'rideReq': 'Ride Requests',
          'noRideReq': 'No ride requests found.',
          'enterPhone': "Enter Phone Number",
          'submit': "Submit",
          'cancel': "Cancel",
          'emailLogin': "Login with Email",
          'googleLogin': "Login with Google",
          'facebookLogin': "Login with Facebook",
          'appleLogin': "Login with Apple",
          'tripDetails': "Trip Details",
          'rider': "Rider:",
          'phone': "Phone:",
          'pickA': "Pickup Address:",
          'destA': "Destination Address:",
          'fair': "Fare:",
          'complete': "Complete",
          'cancel': "Cancel",
        },
        'de_DE': {
          'cab_go': 'CabGo Treiber',
          'login': 'Einloggen',
          'logout': 'Ausloggen',
          'home': 'Zuhause',
          'search': 'Suche',
          'get_started': 'Loslegen',
          'letsRide': 'Lass uns reiten',
          'rideReq': 'Fahranfragen',
          'noRideReq': 'Keine Fahrtanfragen gefunden',
          'enterPhone': "Telefonnummer eingeben",
          'submit': "einreichen",
          'cancel': "stornieren",
          'emailLogin': "Melden Sie sich mit E-Mail an",
          'googleLogin': "Melden Sie sich mit Google an",
          'facebookLogin': "Mit Facebook einloggen",
          'appleLogin': "Melden Sie sich bei Apple an",
          'tripDetails': "Reisedetails",
          'rider': "Fahrer/Fahrerin:",
          'phone': "Telefon:",
          'pickA': "Abholadresse:",
          'destA': "Zieladresse:",
          'fair': "Fahrpreis:",
          'complete': "Vollständig",
          'cancel': "Stornieren",
        }
      };
}
